import cv2
import random
img = cv2.imread("/Users/muhammadtaqiriaz/Documents/opencv/img_1.jfif",1)
startpoint = (0,0)
endpoint = (70,70)
r = random.randint(1,255)
g = random.randint(1,255)
b = random.randint(1,255)
color = (r,g,b)
thickness = (5)
imgline = cv2.line(img,startpoint,endpoint,color,thickness)
cv2.imshow("Image line",imgline)
img = cv2.imread("/Users/muhammadtaqiriaz/Documents/opencv/img_1.jfif",1)
startpoint2 = (50,50)
endpoint2 = (120,120)
r2 = random.randint(1,255)
g2 = random.randint(1,255)
b2 = random.randint(1,255)
color2 = (r2,g2,b2)
imgrect = cv2.rectangle(img,startpoint2,endpoint2,color2,thickness)
cv2.imshow("Image rectangle",imgrect)
img = cv2.imread("/Users/muhammadtaqiriaz/Documents/opencv/img_1.jfif",1)
r3 = random.randint(1,255)
g3 = random.randint(1,255)
b3 = random.randint(1,255)
color3 = (r3,g3,b3)
thicknessf = (-2)
imgrectf = cv2.rectangle(img,startpoint2,endpoint2,color3,thicknessf)
cv2.imshow("Image rectangle filled",imgrectf)
img = cv2.imread("/Users/muhammadtaqiriaz/Documents/opencv/img_1.jfif",1)
center = (150,85)
radius = 15
r4 = random.randint(1,255)
g4 = random.randint(1,255)
b4 = random.randint(1,255)
color4 = (r4,g4,b4)
imgcircle = cv2.circle(img,center,radius,color4,thickness)
cv2.imshow("Image circle",imgcircle)
img = cv2.imread("/Users/muhammadtaqiriaz/Documents/opencv/img_1.jfif",1)
r5 = random.randint(1,255)
g5 = random.randint(1,255)
b5 = random.randint(1,255)
color5 = (r5,g5,b5)
imgcirclef = cv2.circle(img,center,radius,color5,thicknessf)
cv2.imshow("Image circle filled",imgcirclef)
img = cv2.imread("/Users/muhammadtaqiriaz/Documents/opencv/img_1.jfif",1)
font = cv2.FONT_HERSHEY_COMPLEX
position = (0,75)
size = (1.5)
r6 = random.randint(1,255)
g6 = random.randint(1,255)
b6 = random.randint(1,255)
color6 = (r6,g6,b6)
text = ("Hello world")
imgtext = cv2.putText(img,text,position,font,size,color6,thickness,cv2.LINE_AA)
cv2.imshow("Image text",imgtext)
cv2.waitKey(0)