import cv2
import numpy as np
img = cv2.imread("/Users/muhammadtaqiriaz/Documents/opencv/img_1.jfif",1)
cv2.imshow("Image 1",img)
img_big = cv2.resize(img,(500,350))
cv2.imshow("Image 1 resize",img_big)
img_2 = cv2.imread("/Users/muhammadtaqiriaz/Documents/opencv/img_2.jfif",1)
cv2.imshow("Image 2",img_2)
img2_big = cv2.resize(img_2,(500,350))
cv2.imshow("Image 2 resize",img2_big)
img_weighted = cv2.addWeighted(img_big,0.5,img2_big,0.5,-25)
cv2.imshow("Image weighted",img_weighted)
img_subtract = cv2.subtract(img_big,img2_big)
cv2.imshow("Image subrtact",img_subtract)
kernel = np.ones((5,5),np.uint8)
img_erosion = cv2.erode(img,kernel)
cv2.imshow("Image 1 erosion",img_erosion)
img_blur = cv2.GaussianBlur(img,(15,15),0)
cv2.imshow("Image 1 blur",img_blur)
cv2.waitKey(0)